// <auto-generated />
using IOTLabWebApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IOTLabWebApi.Migrations
{
    [DbContext(typeof(IotLabDbContext))]
    [Migration("20170821014957_SedDbWhitModels")]
    partial class SedDbWhitModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IOTLabWebApi.Core.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceComId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("ModelId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("IOTLabWebApi.Core.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnalogInputPins")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DigitalIOPins")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Microcontroller")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("MoreInfo")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("PWMDigitalIOPins")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("IOTLabWebApi.Core.Models.Device", b =>
                {
                    b.HasOne("IOTLabWebApi.Core.Models.Model", "Model")
                        .WithMany("Devices")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
